// <auto-generated />
using System;
using CentroTerapia.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CentroTerapia.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251222054247_AddEspecialidadToTipoSesion")]
    partial class AddEspecialidadToTipoSesion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CentroTerapia.Domain.Entities.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("longblob");

                    b.Property<int?>("TerapeutaId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoSesionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("Fecha");

                    b.HasIndex("PacienteId");

                    b.HasIndex("TipoSesionId");

                    b.HasIndex("TerapeutaId", "Fecha")
                        .IsUnique();

                    b.ToTable("Citas", (string)null);
                });

            modelBuilder.Entity("CentroTerapia.Domain.Entities.Especialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("CentroTerapia.Domain.Entities.Familia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Responsable2Apellido")
                        .HasColumnType("longtext");

                    b.Property<string>("Responsable2DNI")
                        .HasColumnType("longtext");

                    b.Property<string>("Responsable2Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("Responsable2Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Responsable2Relacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Responsable2Telefono")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsablePrincipalApellido")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsablePrincipalDNI")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsablePrincipalDireccion")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsablePrincipalEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsablePrincipalNombre")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsablePrincipalRelacion")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsablePrincipalTelefono")
                        .HasColumnType("longtext");

                    b.Property<string>("TelefonoContacto")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Familias");
                });

            modelBuilder.Entity("CentroTerapia.Domain.Entities.FranjaDisponibilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.Property<bool>("Recurrente")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TerapeutaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TerapeutaId");

                    b.ToTable("FranjasDisponibilidad");
                });

            modelBuilder.Entity("CentroTerapia.Domain.Entities.FranjaExcepcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FranjaId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FranjaId", "Fecha")
                        .IsUnique();

                    b.ToTable("FranjaExcepciones");
                });

            modelBuilder.Entity("CentroTerapia.Domain.Entities.NotaSesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CitaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TerapeutaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CitaId");

                    b.HasIndex("TerapeutaId");

                    b.ToTable("NotaSesion", (string)null);
                });

            modelBuilder.Entity("CentroTerapia.Domain.Entities.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("FamiliaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreContactoEmergencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroContactoEmergencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("CentroTerapia.Domain.Entities.Terapeuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("EspecialidadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Presentacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("Terapeutas");
                });

            modelBuilder.Entity("CentroTerapia.Domain.Entities.Terapia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<int?>("EdadDesde")
                        .HasColumnType("int");

                    b.Property<int?>("EdadHasta")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Requisitos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Terapias");
                });

            modelBuilder.Entity("CentroTerapia.Domain.Entities.TipoSesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("TiposSesion");
                });

            modelBuilder.Entity("CentroTerapia.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CentroTerapia.Domain.Entities.Cita", b =>
                {
                    b.HasOne("CentroTerapia.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentroTerapia.Domain.Entities.Terapeuta", "Terapeuta")
                        .WithMany("Citas")
                        .HasForeignKey("TerapeutaId");

                    b.HasOne("CentroTerapia.Domain.Entities.TipoSesion", "TipoSesion")
                        .WithMany()
                        .HasForeignKey("TipoSesionId");

                    b.Navigation("Paciente");

                    b.Navigation("Terapeuta");

                    b.Navigation("TipoSesion");
                });

            modelBuilder.Entity("CentroTerapia.Domain.Entities.FranjaDisponibilidad", b =>
                {
                    b.HasOne("CentroTerapia.Domain.Entities.Terapeuta", "Terapeuta")
                        .WithMany("Franjas")
                        .HasForeignKey("TerapeutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Terapeuta");
                });

            modelBuilder.Entity("CentroTerapia.Domain.Entities.FranjaExcepcion", b =>
                {
                    b.HasOne("CentroTerapia.Domain.Entities.FranjaDisponibilidad", "Franja")
                        .WithMany()
                        .HasForeignKey("FranjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franja");
                });

            modelBuilder.Entity("CentroTerapia.Domain.Entities.NotaSesion", b =>
                {
                    b.HasOne("CentroTerapia.Domain.Entities.Cita", "Cita")
                        .WithMany()
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentroTerapia.Domain.Entities.Terapeuta", "Terapeuta")
                        .WithMany()
                        .HasForeignKey("TerapeutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Terapeuta");
                });

            modelBuilder.Entity("CentroTerapia.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("CentroTerapia.Domain.Entities.Familia", "Familia")
                        .WithMany("Pacientes")
                        .HasForeignKey("FamiliaId");

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("CentroTerapia.Domain.Entities.Terapeuta", b =>
                {
                    b.HasOne("CentroTerapia.Domain.Entities.Especialidad", "Especialidad")
                        .WithMany("Terapeutas")
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("CentroTerapia.Domain.Entities.TipoSesion", b =>
                {
                    b.HasOne("CentroTerapia.Domain.Entities.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("CentroTerapia.Domain.Entities.Especialidad", b =>
                {
                    b.Navigation("Terapeutas");
                });

            modelBuilder.Entity("CentroTerapia.Domain.Entities.Familia", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("CentroTerapia.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("CentroTerapia.Domain.Entities.Terapeuta", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Franjas");
                });
#pragma warning restore 612, 618
        }
    }
}
